# Generated by Django 5.2.3 on 2025-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share_dinkum_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="costbaseadjustment",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="costbaseadjustmentallocation",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dataexport",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="logentry",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="market",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sharesplit",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
