# Generated by Django 5.2.3 on 2025-07-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share_dinkum_app", "0002_alter_costbaseadjustment_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="market",
            options={},
        ),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                fields=("account", "code"), name="market_keys"
            ),
        ),
    ]
