# Generated by Django 5.2.3 on 2025-08-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share_dinkum_app", "0003_alter_market_options_market_market_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataexport",
            name="include_price_history",
            field=models.BooleanField(
                default=False, help_text="Include price history in the export?"
            ),
        ),
    ]
