# Generated by Django 5.2.3 on 2025-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share_dinkum_app", "0004_dataexport_include_price_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="costbaseadjustmentallocation",
            name="activation_date",
            field=models.DateField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="costbaseadjustmentallocation",
            name="deactivation_date",
            field=models.DateField(editable=False, null=True),
        ),
    ]
