# Generated by Django 5.2.3 on 2025-08-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "share_dinkum_app",
            "0005_costbaseadjustmentallocation_activation_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="sale_date",
            field=models.DateField(editable=False, null=True),
        ),
    ]
