# Generated by Django 5.2.5 on 2025-08-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share_dinkum_app", "0006_parcel_sale_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="calculated_instrument_name",
            field=models.CharField(
                blank=True, editable=False, max_length=16, null=True
            ),
        ),
    ]
