# Generated by Django 5.2.5 on 2025-08-09 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("share_dinkum_app", "0007_parcel_calculated_instrument_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parcel",
            old_name="calculated_unsold_quantity",
            new_name="calculated_remaining_quantiy",
        ),
    ]
