# Generated by Django 5.2.5 on 2025-08-09 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "share_dinkum_app",
            "0008_rename_calculated_unsold_quantity_parcel_calculated_remaining_quantiy",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="parcel",
            old_name="calculated_remaining_quantiy",
            new_name="calculated_remaining_quantity",
        ),
    ]
