# Generated by Django 5.2.5 on 2025-08-14 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "share_dinkum_app",
            "0009_rename_calculated_remaining_quantiy_parcel_calculated_remaining_quantity",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="costbaseadjustmentallocation",
            name="cost_base_adjustment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cost_base_adjustment_allocation",
                to="share_dinkum_app.costbaseadjustment",
            ),
        ),
    ]
