# Generated by Django 5.2.5 on 2025-09-06 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("share_dinkum_app", "0011_alter_logentry_content_type_currentexchangerate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currentexchangerate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="currentexchangerate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="currentexchangerate",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="currentexchangerate",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="currentexchangerate",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="description",
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="legacy_id",
        ),
        migrations.RemoveField(
            model_name="exchangerate",
            name="notes",
        ),
        migrations.AlterField(
            model_name="currentexchangerate",
            name="account",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="share_dinkum_app.account",
            ),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="account",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="share_dinkum_app.account",
            ),
        ),
    ]
