# Generated by Django 5.2.7 on 2026-02-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0012_remove_currentexchangerate_created_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='instrumentpricehistory',
            index=models.Index(fields=['account', 'instrument', 'date'], name='instrument_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='instrumentpricehistory',
            constraint=models.UniqueConstraint(fields=('account', 'instrument', 'date'), name='instrument_price_history_keys'),
        ),
    ]
