# Generated by Django 6.0.3 on 2026-08-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0013_instrumentpricehistory_instrument_date_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('owner', 'description'), name='account_keys'),
        ),
    ]
