# Generated by Django 6.0.3 on 2026-08-31 00:07

import datetime
import django.db.models.deletion
import share_dinkum_app.uuid_future
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0014_account_account_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGTReturnSnapshot',
            fields=[
                ('id', models.UUIDField(default=share_dinkum_app.uuid_future.uuid7, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.CharField(blank=True, editable=False, max_length=36, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('taken_at', models.DateField(default=datetime.date.today, help_text='The day these figures were captured.')),
                ('basis', models.CharField(choices=[('LEGACY', 'Flat 50% discount, residency not declared'), ('DIVISION_115', 'Division 115, apportioned for declared residency')], default='LEGACY', max_length=16)),
                ('engine_version', models.CharField(blank=True, help_text='Application version that produced the figures.', max_length=32)),
                ('payload', models.TextField(blank=True, default='', editable=False)),
                ('is_lodged', models.BooleanField(default=False, help_text='Were these the figures actually lodged?')),
                ('lodged_at', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='share_dinkum_app.account')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cgt_return_snapshot', to='share_dinkum_app.fiscalyear')),
            ],
            options={
                'ordering': ['fiscal_year', 'taken_at'],
                'constraints': [models.UniqueConstraint(fields=('account', 'fiscal_year', 'taken_at'), name='cgt_return_snapshot_keys')],
            },
        ),
    ]
