# Generated by Django 6.0.3 on 2026-09-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0015_account_tax_settings_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='model_2027_regime',
            field=models.BooleanField(default=False, help_text='Model the 2027 capital gains changes for disposals from 1 July 2027. Figures for those years are projections, and the schedule says so. Nothing before that date changes.'),
        ),
    ]
