# Generated by Django 6.0.3 on 2026-08-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0015_cgtreturnsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='cgt_asset_category_override',
            field=models.CharField(blank=True, help_text='Only if the category derived from the legal form and market is wrong.', max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='is_taxable_australian_property',
            field=models.BooleanField(blank=True, help_text="Leave unset unless this is real property or a non-portfolio interest in a land rich entity. Ordinary listed shares are not taxable Australian property by nature; where they are, it is because of the holder's own circumstances rather than the instrument.", null=True),
        ),
        migrations.AddField(
            model_name='instrument',
            name='legal_form',
            field=models.CharField(choices=[('UNKNOWN', 'Not yet classified'), ('COMPANY', 'Company - ordinary or preference shares, including listed investment companies'), ('UNIT_TRUST', 'Unit trust - most ETFs, managed funds and property trusts'), ('STAPLED', 'Stapled security - a share and a unit traded together'), ('RIGHT_OPTION', 'Right, option or entitlement'), ('DEBT', 'Note, bond or other debt interest'), ('REAL_PROPERTY', 'Direct interest in real property'), ('COLLECTABLE', 'Collectable'), ('OTHER', 'Other CGT asset')], default='UNKNOWN', help_text='Shown on the product disclosure statement or annual tax statement.', max_length=13),
        ),
        migrations.AddField(
            model_name='instrument',
            name='legal_form_source',
            field=models.CharField(choices=[('DEFAULT', 'Not set'), ('SUGGESTED', 'Suggested from the code or market data'), ('USER', 'Confirmed by you')], default='DEFAULT', editable=False, max_length=9),
        ),
        migrations.AddField(
            model_name='market',
            name='country',
            field=models.CharField(blank=True, help_text='ISO country code, e.g. AU. Decides whether instruments here are treated as Australian listed for capital gains reporting.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='is_exchange_listed',
            field=models.BooleanField(default=True, help_text='Uncheck for unlisted holdings. Unlisted assets fall into the "other" categories on the CGT schedule regardless of country.'),
        ),
    ]
