# Generated by Django 6.0.3 on 2026-09-29 13:16

from decimal import Decimal
from django.db import migrations, models
from django.db.models import F


def mark_stand_in_rates(apps, schema_editor):
    """A cross-currency rate of exactly 1.0 was left by a failed fetch, so flag it.

    It is then fetched again, and the history refresh replaces it.
    """
    ExchangeRate = apps.get_model('share_dinkum_app', 'ExchangeRate')
    ExchangeRate.objects.exclude(convert_from=F('convert_to')).filter(
        exchange_rate_multiplier=Decimal('1')).update(is_placeholder=True)


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0016_account_model_2027_regime'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerate',
            name='is_placeholder',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='cumulative_split_multiplier',
            field=models.DecimalField(decimal_places=10, default=Decimal('1.0'), editable=False, max_digits=22),
        ),
        migrations.RunPython(mark_stand_in_rates, migrations.RunPython.noop),
    ]
