# Generated by Django 6.0.3 on 2026-08-31 08:18

import django.db.models.deletion
import share_dinkum_app.uuid_future
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0017_attributionstatement_attributioncomponent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidencyPeriod',
            fields=[
                ('id', models.UUIDField(default=share_dinkum_app.uuid_future.uuid7, editable=False, primary_key=True, serialize=False)),
                ('legacy_id', models.CharField(blank=True, editable=False, max_length=36, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RESIDENT', 'Australian resident'), ('FOREIGN', 'Foreign resident'), ('TEMPORARY', 'Temporary resident')], max_length=9)),
                ('start_date', models.DateField(help_text='First day of this period.')),
                ('end_date', models.DateField(blank=True, help_text='Last day of this period. Leave blank if ongoing.', null=True)),
                ('i1_election_made', models.BooleanField(blank=True, help_text='Where this period begins a departure from Australia: did you choose under s104-165(2) to disregard the deemed disposal on ceasing residency? If so, the assets you held then stay within the Australian CGT net until you sell them.', null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='share_dinkum_app.account')),
            ],
            options={
                'ordering': ['start_date'],
                'constraints': [models.UniqueConstraint(fields=('account', 'start_date'), name='residency_period_keys')],
            },
        ),
    ]
