# Generated by Django 6.0.3 on 2026-09-30 09:45

import django.core.validators
import share_dinkum_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0017_exchange_rate_placeholder_and_split_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=16, validators=[share_dinkum_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='dividend',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=16, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='sell',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=16, validators=[share_dinkum_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='sharesplit',
            name='date',
            field=models.DateField(help_text='The ex-date. Trades on it are already in post-split units, so only parcels bought before it are split.'),
        ),
        migrations.AlterField(
            model_name='sharesplit',
            name='quantity_after',
            field=models.DecimalField(decimal_places=4, max_digits=16, validators=[share_dinkum_app.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='sharesplit',
            name='quantity_before',
            field=models.DecimalField(decimal_places=4, max_digits=16, validators=[share_dinkum_app.models.validate_positive]),
        ),
    ]
