# Generated by Django 6.0.3 on 2026-08-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0018_residencyperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='tax_settings_reviewed_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='taxpayer_type',
            field=models.CharField(choices=[('UNDECLARED', 'Not declared'), ('INDIVIDUAL', 'Individual'), ('TRUST', 'Trust'), ('PARTNERSHIP', 'Partnership'), ('COMPANY', 'Company'), ('SMSF', 'Complying superannuation fund')], default='UNDECLARED', help_text='Who owns this portfolio for tax purposes.', max_length=11),
        ),
    ]
