# Generated by Django 6.0.3 on 2026-10-03 10:21

import share_dinkum_app.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0019_column_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividend',
            name='corporate_tax_rate_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.0'), help_text='Enter a percentage value (e.g., 25.00 for 25%)', max_digits=5, validators=[share_dinkum_app.models.validate_company_tax_rate]),
        ),
    ]
