# Generated by Django 6.0.3 on 2026-10-04 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0020_dividend_company_tax_rate_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributioncomponent',
            name='component',
            field=models.CharField(choices=[('DISCOUNTED_TAP', 'Discounted capital gains - taxable Australian property'), ('DISCOUNTED_NTAP', 'Discounted capital gains - non-taxable Australian property'), ('OTHER_TAP', 'Other method capital gains - taxable Australian property'), ('OTHER_NTAP', 'Other method capital gains - non-taxable Australian property'), ('FOREIGN_CG_DISCOUNTED', 'Taxable foreign capital gains - discounted method'), ('FOREIGN_CG_OTHER', 'Taxable foreign capital gains - other method'), ('AMIT_GROSS_UP', 'AMIT CGT gross up amount'), ('NET_CAPITAL_GAIN', 'Net capital gain'), ('TOTAL_CY_CG', 'Total current year capital gains'), ('OTHER_CG_DISTRIBUTION', 'Other capital gains distribution'), ('COSTBASE_INCREASE', 'AMIT cost base net amount - shortfall (increase cost base)'), ('COSTBASE_DECREASE', 'AMIT cost base net amount - excess (reduce cost base)'), ('TAX_DEFERRED', 'Tax-deferred amount (reduces cost base)'), ('CGT_CONCESSION', 'CGT concession amount (does not adjust cost base)'), ('TAX_FREE', 'Tax-free amount (reduces reduced cost base only)'), ('TAX_EXEMPT', 'Tax-exempt amount (reduces reduced cost base only)'), ('NON_ATTRIBUTABLE', 'Other non-attributable amount (reduces cost base)'), ('FRANKED_DISTRIBUTION', 'Franked distributions from trusts'), ('FRANKING_CREDIT', 'Franking credits'), ('UNFRANKED_DISTRIBUTION', 'Unfranked distributions'), ('INTEREST', 'Interest'), ('OTHER_INCOME', 'Other income'), ('FOREIGN_SOURCE_INCOME', 'Assessable foreign source income'), ('FOREIGN_INCOME_TAX_OFFSET', 'Foreign income tax offset'), ('NON_ASSESSABLE_NON_EXEMPT', 'Non-assessable non-exempt amount'), ('WITHHOLDING_CREDIT', 'Credit for foreign resident withholding amounts'), ('WITHHOLDING_DEDUCTED', 'Non-resident tax withheld')], help_text='Which line of the statement this is.', max_length=26),
        ),
    ]
