# Generated by Django 6.0.3 on 2026-10-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0021_attribution_franking_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributionstatement',
            name='gain_subject_to_mit_withholding',
            field=models.BooleanField(default=False, help_text='Tick only if you were a foreign resident when paid and the fund withheld managed investment trust (MIT) withholding tax on the taxable Australian property part of its capital gain. That tax is final, so the gain is left out of the capital gains schedule (s840-815). Leave unticked otherwise: a resident, or a fund that did not withhold, still reports the gain.'),
        ),
    ]
