# Generated by Django 6.0.3 on 2026-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0021_remove_cgtreturnsnapshot_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='cgt_asset_category_override',
            field=models.CharField(blank=True, choices=[('Shares in Australian listed companies', 'Shares in Australian listed companies'), ('Other shares', 'Other shares'), ('Units in Australian listed unit trusts', 'Units in Australian listed unit trusts'), ('Other units', 'Other units'), ('Australian real estate', 'Australian real estate'), ('Overseas real estate', 'Overseas real estate'), ('Collectables', 'Collectables'), ('Other assets', 'Other assets')], help_text='Leave empty. Only set this if the category worked out from the legal form and the market is wrong for this holding.', max_length=48, null=True),
        ),
    ]
