# Generated by Django 6.0.3 on 2026-09-02 13:04

from django.db import migrations, models


#: The categories used to be stored as their own display labels. The value is now a stable
#: code, so anything already recorded has to be translated rather than left behind as a
#: string that no longer matches any category -- which would read as "unclassified" and
#: quietly turn a finished schedule into a draft.
LABEL_TO_CODE = {
    'Shares in Australian listed companies': 'AU_LISTED_SHARES',
    'Other shares': 'OTHER_SHARES',
    'Units in Australian listed unit trusts': 'AU_LISTED_UNITS',
    'Other units': 'OTHER_UNITS',
    'Australian real estate': 'AU_REAL_ESTATE',
    'Overseas real estate': 'OVERSEAS_REAL_ESTATE',
    'Collectables': 'COLLECTABLES',
    'Other assets': 'OTHER_ASSETS',
    'Unclassified': 'UNCLASSIFIED',
}


def labels_to_codes(apps, schema_editor):
    Instrument = apps.get_model('share_dinkum_app', 'Instrument')
    for label, code in LABEL_TO_CODE.items():
        Instrument.objects.filter(cgt_asset_category_override=label).update(
            cgt_asset_category_override=code)


def codes_to_labels(apps, schema_editor):
    Instrument = apps.get_model('share_dinkum_app', 'Instrument')
    for label, code in LABEL_TO_CODE.items():
        Instrument.objects.filter(cgt_asset_category_override=code).update(
            cgt_asset_category_override=label)


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0022_alter_instrument_cgt_asset_category_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='cgt_asset_category_override',
            field=models.CharField(blank=True, choices=[('AU_LISTED_SHARES', 'Shares in Australian listed companies'), ('OTHER_SHARES', 'Other shares'), ('AU_LISTED_UNITS', 'Units in Australian listed unit trusts'), ('OTHER_UNITS', 'Other units'), ('AU_REAL_ESTATE', 'Australian real estate'), ('OVERSEAS_REAL_ESTATE', 'Overseas real estate'), ('COLLECTABLES', 'Collectables'), ('OTHER_ASSETS', 'Other assets')], help_text='Leave empty. Only set this if the category worked out from the legal form and the market is wrong for this holding.', max_length=48, null=True),
        ),
            migrations.RunPython(labels_to_codes, codes_to_labels),
    ]
