# Generated by Django 6.0.3 on 2026-10-10 02:24

from typing import Any

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def record_the_buy_each_sale_used(apps: Any, schema_editor: Any) -> None:
    """Copy each allocation's buy from its parcel. Additive: nothing else changes."""
    SellAllocation = apps.get_model('share_dinkum_app', 'SellAllocation')
    Parcel = apps.get_model('share_dinkum_app', 'Parcel')
    SellAllocation.objects.filter(buy__isnull=True).update(
        buy_id=Subquery(Parcel.objects.filter(pk=OuterRef('parcel_id')).values('buy_id')[:1]))


class Migration(migrations.Migration):

    dependencies = [
        ('share_dinkum_app', '0022_statement_mit_withholding'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='holdings_differ',
            field=models.BooleanField(blank=True, default=None, editable=False, help_text='Whether the parcels stored for this instrument give different figures from those worked out again from its trades. Blank until checked. Set by the app; do not edit.', null=True),
        ),
        migrations.AddField(
            model_name='sellallocation',
            name='buy',
            field=models.ForeignKey(blank=True, editable=False, help_text='The buy the units were taken from. Set by the app from the parcel; do not edit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sold_by', to='share_dinkum_app.buy'),
        ),
        migrations.RunPython(record_the_buy_each_sale_used, migrations.RunPython.noop),
    ]
